apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-planner-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-planner-api
  template:
    metadata:
      labels:
        app: travel-planner-api
    spec:
      containers:
        - name: travel-planner-api
          image: sastravelplanneracr.azurecr.io/travel-planner-api:1.0.0-SNAPSHOT
          env:
            - name: ALLOWED_ORIGIN
              value: http://www.sastravelplanner.online,http://sastravelplanner.online
          envFrom:
            - secretRef:
                name: db-secret
            - configMapRef:
                name: db-configmap
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: travel-planner-api-service
spec:
  selector:
    app: travel-planner-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
