package br.com.sas.travel.criteria.model;

public enum ActivityType {

	ADVENTURE_ACTIVITIES,
	ART_AND_CRAFT_WORKSHOPS,
	CULTURAL_TOURS,
	ENTERTAINMENT_SHOWS,
	FAMILY_FRIENDLY,
	HISTORICAL_TOURS,
	NATURE_EXCURSIONS,
	SHOPPING_DISTRICTS,
	SPORTS_AND_RECREATION,
	WATER_SPORTS,
	WELLNESS_RETREATS,

}
