package br.com.sas.travel.criteria.model;

public enum CulturalPreference {

	ARCHITECTURAL_STYLES,
	ART_MUSEUMS,
	CONTEMPORARY_ARTS,
	CULINARY_TRADITIONS,
	CULTURAL_ETIQUETTE,
	CULTURAL_EXCHANGE,
	CULTURAL_HERITAGE_MUSEUMS,
	CULTURAL_LANDSCAPES,
	CULTURAL_PERFORMANCES,
	CULTURAL_WORKSHOPS,
	ETHNIC_DIVERSITY,
	HANDICRAFTS_ARTISAN_MARKETS,
	HERITAGE_PRESERVATION,
	HISTORICAL_SIGNIFICANCE,
	LANGUAGE_LITERATURE,
	LITERARY_FILM_CONNECTIONS,
	LOCAL_CLOTHING_FASHION,
	LOCAL_FESTIVALS_EVENTS,
	MUSIC_DANCE_FORMS,
	RELIGIOUS_HERITAGE,

}
