server:
  port: 8080
spring:
  cors:
    allowed-origins: ${ALLOWED_ORIGIN:http://localhost:3000,http://www.sastravelplanner.online}
  data:
    cosmos:
      uri: ${COSMOS_URI}
      key: ${COSMOS_PRIMARY_KEY}
      secondaryKey: ${COSMOS_SECONDARY_KEY}
      databaseName: ${COSMOS_DATABASE_NAME}
  main:
    allow-bean-definition-overriding: true
