openapi: 3.0.0

info:
  title: Travel Planning API
  version: 1.0.0

servers:
  - description: Travel Planner API
    url: 'https://travelplanner.sas.com.br/api/v1'
    variables:
      stage:
        default: production
        enum:
          - production
          - staging
          - qa
  - description: Local
    url: '{schema}://{host}:{port}{path}'
    variables:
      schema:
        default: https
        enum:
          - https
          - http
      host:
        default: localhost
      port:
        default: '8080'
      path:
        default: /api/v1

paths:
  /travel:
    post:
      summary: Get travel options based on search term
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TravelPlanningRequest'
      responses:
        '200':
          description: Stream of events with travel options
          content:
            text/event-stream:
              schema:
                type: array
                format: event-stream
                items:
                  $ref: '#/components/schemas/TravelPlanningResponse'

components:
  schemas:

    TravelPlanningRequest:
      type: object
      properties:
        searchTerm:
          $ref: '#/components/schemas/SearchTerm'

    TravelPlanningResponse:
      type: object
      discriminator:
        propertyName: type
        mapping:
          criteria: '#/components/schemas/TravelPlanningCriteriaResponse'
          destination: '#/components/schemas/DestinationOptionsResponse'
          flightplan: '#/components/schemas/FlightPlanOptionsResponse'
          accommodation: '#/components/schemas/AccommodationOptionsResponse'
          activity: '#/components/schemas/ActivityOptionsResponse'
          traveltip: '#/components/schemas/TravelTipsResponse'
          optimal: '#/components/schemas/OptimalTravelPlanningResponse'

      properties:
        type:
          type: string
          enum:
            - criteria
            - destination
            - flightplan
            - accommodation
            - activity
            - traveltip
            - optimal
    
    TravelPlanningCriteriaResponse:
      allOf:
        - $ref: '#/components/schemas/TravelPlanningResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/TravelPlanningCriteria'
    
    DestinationOptionsResponse:
      allOf:
        - $ref: '#/components/schemas/TravelPlanningResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/DestinationOptions'
    
    FlightPlanOptionsResponse:
      allOf:
        - $ref: '#/components/schemas/TravelPlanningResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/FlightPlanOptions'
    
    AccommodationOptionsResponse:
      allOf:
        - $ref: '#/components/schemas/TravelPlanningResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/AccommodationOptions'
    
    ActivityOptionsResponse:
      allOf:
        - $ref: '#/components/schemas/TravelPlanningResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/ActivityOptions'
    
    TravelTipsResponse:
      allOf:
        - $ref: '#/components/schemas/TravelPlanningResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/TravelTips'
    
    OptimalTravelPlanningResponse:
      allOf:
        - $ref: '#/components/schemas/TravelPlanningResponse'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/OptimalTravelPlanning'

    SearchTerm:
      type: string
      description: Represents the search term used to specify the trip's requirements.

    TravelPlanningCriteria:
      type: object
      description: Represents the criteria used for planning a trip.
      properties:
        searchTerm:
          $ref: '#/components/schemas/SearchTerm'
        weather:
          $ref: '#/components/schemas/WeatherCriteria'
        language:
          $ref: '#/components/schemas/LanguageCriteria'
        budget:
          $ref: '#/components/schemas/BudgetCriteria'
        lifestyle:
          $ref: '#/components/schemas/LifestyleCriteria'
        departureDateRange:
          $ref: '#/components/schemas/DateRange'
        arrivalDateRange:
          $ref: '#/components/schemas/DateRange'
        activity:
          $ref: '#/components/schemas/ActivityCriteria'
        culture:
          $ref: '#/components/schemas/CulturalCriteria'
        destinationCode:
          type: string
          description: Code of the most scored destination
        withPets:
          type: boolean
          description: Indicates whether the traveler will be accompanied by pets.
        withChildren:
          type: boolean
          description: Indicates whether the traveler will be accompanied by children.

    WeatherCriteria:
      type: object
      description: Represents criteria related to weather conditions.
      properties:
        temperature:
          type: object
          properties:
            min:
              type: number
              description: Minimum desired temperature.
            max:
              type: number
              description: Maximum desired temperature.
        conditions:
          type: array
          items:
            type: string
          description: List of desired weather conditions.

    BudgetCriteria:
      type: object
      description: Represents budget constraints for the trip.
      properties:
        classification:
          type: string
          description: The classification of how much the trip can cost.
          enum:
            - "MINIMUM"
            - "LOW"
            - "MID_RANGE"
            - "MODERATE"
            - "HIGH"
            - "LUXURY"
            - "UNLIMITED"

    LifestyleCriteria:
      type: object
      description: Represents lifestyle preferences for accommodations and activities.
      properties:
        accommodationPreferences:
          type: array
          items:
            $ref: '#/components/schemas/AccommodationType'
        foodPreferences:
          type: array
          items:
            type: string
            enum:
              - "BUFFET"
              - "CAFE"
              - "CASUAL_DINING"
              - "ETHNIC_CUISINE"
              - "FAMILY_FRIENDLY"
              - "FARM_TO_TABLE"
              - "FAST_FOOD"
              - "FINE_DINING"
              - "FOOD_TRUCK"
              - "VEGETARIAN_VEGAN"

    ActivityCriteria:
      type: object
      description: Represents preferences for activities during the trip.
      properties:
        activityPreferences:
          type: array
          items:
            $ref: '#/components/schemas/ActivityType'
          description: Preferred types of activity.
        difficultyLevel:
          $ref: '#/components/schemas/ActivityDifficulty'

    CulturalCriteria:
      type: object
      properties:
        culturalPreferences:
          type: array
          items:
            type: string
            enum:
              - "ARCHITECTURAL_STYLES"
              - "ART_MUSEUMS"
              - "CONTEMPORARY_ARTS"
              - "CULINARY_TRADITIONS"
              - "CULTURAL_ETIQUETTE"
              - "CULTURAL_EXCHANGE"
              - "CULTURAL_HERITAGE_MUSEUMS"
              - "CULTURAL_LANDSCAPES"
              - "CULTURAL_PERFORMANCES"
              - "CULTURAL_WORKSHOPS"
              - "ETHNIC_DIVERSITY"
              - "HANDICRAFTS_ARTISAN_MARKETS"
              - "HERITAGE_PRESERVATION"
              - "HISTORICAL_SIGNIFICANCE"
              - "LANGUAGE_LITERATURE"
              - "LITERARY_FILM_CONNECTIONS"
              - "LOCAL_CLOTHING_FASHION"
              - "LOCAL_FESTIVALS_EVENTS"
              - "MUSIC_DANCE_FORMS"
              - "RELIGIOUS_HERITAGE"
      description: Represents cultural preferences for the destination.

    LanguageCriteria:
      type: object
      properties:
        languageProficiencies:
          type: array
          items:
            $ref: '#/components/schemas/LanguageProficiency'

    LanguageProficiency:
      type: object
      properties:
        language:
          type: string
        proficiency:
          type: string
          enum:
            - "BASIC"
            - "INTERMEDIATE"
            - "ADVANCED"
            - "FLUENT"  

    DateRange:
      type: object
      description: Represents a range of dates.
      properties:
        startDate:
          type: string
          format: date
          description: Start date of the range.
        endDate:
          type: string
          format: date
          description: End date of the range.

    AccommodationType:
      type: string
      enum:
        - "APARTMENT_HOTEL"
        - "B_AND_B"
        - "BOUTIQUE_HOTEL"
        - "GUEST_HOUSE"
        - "HOSTEL"
        - "HOTEL"
        - "INN"
        - "RESORT"
        - "VACATION_RENTAL"

    ActivityType:
      type: string
      enum:
        - "ADVENTURE_ACTIVITIES"
        - "ART_AND_CRAFT_WORKSHOPS"
        - "CULTURAL_TOURS"
        - "ENTERTAINMENT_SHOWS"
        - "FAMILY_FRIENDLY"
        - "HISTORICAL_TOURS"
        - "NATURE_EXCURSIONS"
        - "SHOPPING_DISTRICTS"
        - "SPORTS_AND_RECREATION"
        - "WATER_SPORTS"
        - "WELLNESS_RETREATS"

    ActivityDifficulty:
      type: string
      enum:
        - "ADVANCED"
        - "CHALLENGING"
        - "EASY"
        - "EXPERT"
        - "MODERATE"
      description: Difficulty level of the activity.

    DestinationOptions:
      type: object
      properties:
        criteria:
          $ref: '#/components/schemas/TravelPlanningCriteria'
        options:
          type: array
          items:
            $ref: '#/components/schemas/Destination'

    Destination:
      allOf:
        - $ref: '#/components/schemas/TravelOptionBase'
        - type: object
          description: Represents a trip destination recommendation.
          properties:
            destination:
              type: string
              description: The recommended destination for the trip.
            code:
              type: string
              description: The unique identifier of the destination.

    TravelOptionBase:
      type: object
      properties:
        score:
          $ref: '#/components/schemas/Score'
        rating:
          $ref: '#/components/schemas/Rating'

    Rating:
      type: number
      minimum: 1
      maximum: 5
      description: "A numerical rating between 1 and 5 (inclusive)."

    Score:
      type: number
      minimum: 1
      maximum: 5
      description: 'The similarity score indicating how well the result matches the criteria.'

    FlightPlanOptions:
      type: object
      properties:
        criteria:
          $ref: '#/components/schemas/TravelPlanningCriteria'
        options:
          type: array
          items:
            $ref: '#/components/schemas/FlightPlan'

    FlightPlan:
      allOf:
        - $ref: '#/components/schemas/TravelOptionBase'
        - type: object
          properties:
            returnFlight:
              $ref: '#/components/schemas/Flight'
            outwardFlight:
              $ref: '#/components/schemas/Flight'

    Flight:
      type: object
      properties:
        code:
          type: string
          description: unique identifier of the flight
        departure:
          type: string
          format: date-time
        arrival:
          type: string
          format: date-time
        airport:
          $ref: '#/components/schemas/Airport'

    Airport:
      type: object
      properties:
        code:
          type: string
          pattern: '^[A-Z]{3}$'
          description: unique identifier of the airport containing 3 capital letters
        name:
          type: string
        address:
          type: string

    AccommodationOptions:
      type: object
      properties:
        criteria:
          $ref: '#/components/schemas/TravelPlanningCriteria'
        options:
          type: array
          items:
            $ref: '#/components/schemas/Accommodation'

    Accommodation:
      allOf:
        - $ref: '#/components/schemas/TravelOptionBase'
        - type: object
          description: Represents an accommodation recommendation.
          properties:
            code:
              type: string
              description: unique identifier of the accommodation
            name:
              type: string
            address:
              type: string
            type:
              $ref: '#/components/schemas/AccommodationType'

    ActivityOptions:
      type: object
      properties:
        criteria:
          $ref: '#/components/schemas/TravelPlanningCriteria'
        options:
          type: array
          items:
            $ref: '#/components/schemas/Activity'

    Activity:
      allOf:
        - $ref: '#/components/schemas/TravelOptionBase'
        - type: object
          description: Represents an activity recommendation.
          properties:
            code:
              type: string
              description: unique identifier of the activity
            name:
              type: string
            description:
              type: string
            address:
              type: string
            type:
              $ref: '#/components/schemas/ActivityType'
            difficulty:
              $ref: '#/components/schemas/ActivityDifficulty'

    TravelTips:
      type: object
      properties:
        criteria:
          $ref: '#/components/schemas/TravelPlanningCriteria'
        options:
          type: array
          items:
            $ref: '#/components/schemas/TravelTip'

    TravelTip:
      allOf:
        - $ref: '#/components/schemas/TravelOptionBase'
        - type: object
          properties:
            content:
              type: string

    OptimalTravelPlanning:
      type: object
      description: Represents the best travel option based on search criteria.
      properties:
        criteria:
          $ref: '#/components/schemas/TravelPlanningCriteria'
        destination:
          $ref: '#/components/schemas/Destination'
        flightPlan:
          $ref: '#/components/schemas/FlightPlan'
        accommodation:
          $ref: '#/components/schemas/Accommodation'
        activities:
          type: array
          items:
            $ref: '#/components/schemas/Activity'
        tips:
          type: array
          items:
            $ref: '#/components/schemas/TravelTip'