name: 
replicaCount: 1
configmap:
  name: db-configmap
  data:
    COSMOS_URI: 
    COSMOS_DATABASE_NAME: 
secret:
  name: db-secret
  data:
    COSMOS_PRIMARY_KEY: 
    COSMOS_SECONDARY_KEY: 
image: 
  registry: 
  repository:
  tag:  
