apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: travel-planner-api
  template:
    metadata:
      annotations:
      labels:
        app: travel-planner-api
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: ALLOWED_ORIGINS
              value: {{ .Values.allowedOrigins }}
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
          ports:
            - containerPort: 8080 
      imagePullSecrets:
        - name: acr-secret