apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  COSMOS_PRIMARY_KEY: {{ .Values.secret.data.COSMOS_PRIMARY_KEY }}
  COSMOS_SECONDARY_KEY: {{ .Values.secret.data.COSMOS_SECONDARY_KEY }}