apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.resourceGroup }}
    service.beta.kubernetes.io/azure-pip-name: {{ .Values.network.publicIp }}
spec:
  selector:
    app: travel-planner-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer