apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: travel-planner-web
  template:
    metadata:
      labels:
        app: travel-planner-web
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-secret
