apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}-service"
spec:
  selector:
    app: travel-planner-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
