name: Simple Deploy Travel Planner API

on:
  push:
    branches: 
      - 'main'
    paths:
      - 'api/**'
      - '.github/workflows/api.yaml'

env:
  API_ENTRYPOINT_NAME: 'travel-planner-api'
      
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Set Version
        id: maven
        run: echo ::set-output name=version::$(mvn -f api/pom.xml -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)

      - name: Maven Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'
      
      - name: Maven Build
        run: mvn -f api/pom.xml clean install -DskipTests

      - name: Docker Build and Push
        uses: ./.github/actions/docker
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          container: ${{ env.API_ENTRYPOINT_NAME }}
          tag: ${{ steps.maven.outputs.version }}
          path: 'api'

      - name: Azure Setup
        uses: ./.github/actions/azure
        with:
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
          dns-zone: ${{ secrets.AZURE_DNS_ZONE }}
          a-record: 'api'

      - name: Deploy API
        run: >-
          helm upgrade --install travel-planner-api ./infra/helm/charts/api \
            --namespace planner \
            --create-namespace \
            --set image.registry=${{ vars.DOCKER_REGISTRY }} \
            --set image.repository=travel-planner-api \
            --set image.tag=${{ steps.maven.outputs.version }} \
            --set name=travel-planner-api \
            --set configmap.data.COSMOS_URI=${{ vars.DATABASE_URI }} \
            --set configmap.data.COSMOS_DATABASE_NAME=${{ vars.DATABASE_NAME }} \
            --set secret.data.COSMOS_PRIMARY_KEY=${{ vars.DATABASE_SECRET }} \
            --set network.publicIp=$IP_ADDRESS
