name: Simple Deploy Travel Planner API

on:
  push:
    branches: 
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Set Branch
        id: branch
        run: echo "branch=${GITHUB_REF#/refs/heads/}" >> "$GITHUB_ENV"
        
      - name: Set Version
        id: maven
        uses: CptMokoena/maven-get-version-action@1.0.3
        with:
          path: api/pom.xml

      - name: Maven Setup
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '21'
      
      - name: Maven Build
        run: mvn -f api/pom.xml clean install -DskipTests

      - name: Docker Setup
        run: echo ${{secrets.DOCKER_PASSWORD}} | docker login ${{vars.DOCKER_REGISTRY}} -u ${{secrets.DOCKER_USERNAME}} --password-stdin

      - name: Docker Build
        run: docker build -t ${{vars.DOCKER_REGISTRY}}/travel-planner-api:${{ steps.maven.outputs.version }} ./api

      - name: Docker Push
        run: docker push ${{vars.DOCKER_REGISTRY}}/travel-planner-api:${{ steps.maven.outputs.version }}